# Generated by Django 3.2.8 on 2022-08-04 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=0, max_length=150, verbose_name='first_name')),
                ('middle_name', models.CharField(default=0, max_length=150, verbose_name='middle_name')),
                ('last_name', models.CharField(default=0, max_length=150, verbose_name='last_name')),
                ('image', models.FileField(blank=True, default='default.jpg', null=True, upload_to=users.models.get_image_path)),
                ('cover', models.FileField(blank=True, default='default.jpg', null=True, upload_to=users.models.get_cover_path)),
                ('bio', models.TextField(default='', max_length=350, verbose_name='bio')),
                ('city', models.CharField(default='', max_length=30, verbose_name='city')),
                ('country', models.CharField(default='', max_length=30, verbose_name='country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
