# Generated by Django 4.0.6 on 2022-08-07 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=0, max_length=150, verbose_name='first_name')),
                ('middle_name', models.CharField(default=0, max_length=150, verbose_name='middle_name')),
                ('last_name', models.CharField(default=0, max_length=150, verbose_name='last_name')),
                ('position', models.CharField(default='', max_length=300, verbose_name='position')),
                ('image', models.FileField(blank=True, default='default.jpg', null=True, upload_to=users.models.get_image_path)),
                ('cover', models.FileField(blank=True, default='default.jpg', null=True, upload_to=users.models.get_cover_path)),
                ('bio', models.TextField(default='', max_length=500, verbose_name='bio')),
                ('city', models.CharField(default='', max_length=30, verbose_name='city')),
                ('country', models.CharField(default='', max_length=50, verbose_name='country')),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram', models.URLField(blank=True, max_length=500, null=True)),
                ('github', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
