# Generated by Django 4.0.6 on 2022-08-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220804_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(default='', max_length=300, verbose_name='position'),
        ),
    ]
