# Generated by Django 4.0.6 on 2022-07-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authwiki_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='firstname'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='lastname'),
        ),
    ]
