# Generated by Django 4.0.6 on 2022-08-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authwiki_app', '0003_alter_library_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='library',
        ),
    ]
